### ISSUE TITLE
Change todo list style

### ISSUE THREAD

**Issue by yurihoka** [yurihoka/Todolist#18]
## Title
Change style for modern

## Purpose
To show it looks like modern

## Tasks
Break down and manage your tasks.
- [ ] Change color of background
- [ ] Change color of button
- [ ] Add blur as background of each item
