### ISSUE TITLE
Set up the directory

### ISSUE THREAD

**Issue by yurihoka** [yurihoka/Todolist#2]
## Title
Set up directory and files

## Purpose
To start building todolist application

## Tasks
Break down and manage your tasks.
- [x] Create sass folder and scss file
- [x] Create html file
- [x] Create js folder and file
- [x] Do "git init"
