### ISSUE TITLE
Create a desktop design of Todolist

### ISSUE THREAD

**Issue by yurihoka** [yurihoka/Todolist#4]
## Title
Create a desktop design of Todolist (header, input form)

## Purpose
For creating design of Todolist

## Tasks
- [x] Add header section
- [x] Add input form
- [x] Add submit button
