### ISSUE TITLE
Add function to display todo list

### ISSUE THREAD

**Issue by yurihoka** [yurihoka/Todolist#9]
## Title
Add function to display todo list 

## Purpose
To display todo after submit

## Tasks
Break down and manage your tasks.
- [x] Display todo list once click submit button
- [x] Show alert message if it is invalid (input no letter)
- [x] Disappear alert message when typing in input form
- [x] Display "edit" and "delete" button
